#!usr/bin/env bash

_notes_completions() {

    case $COMP_CWORD in
        1) COMPREPLY=($(compgen -W "list l edit e delete d copy cp glow g help h" "${COMP_WORDS[1]}")) ;;
        2) [ ${COMP_WORDS[1]} =~ ^(edit|e|copy|cp|delete|d|glow|g)$ ] && COMPREPLY=$(ls $HOME/notes) ;;
    esac
}

complete -F _notes_completions qnote
